### PR TITLE
Print log when it cannot lookup for an IP

### PR DESCRIPTION
**Pull request by saveav**
## Desc

Perform logging when an IP lookup failed for some reason.

## Effect

Can know why a specific IP lookup failed

### CODE REVIEW

**Comment by ignatiusreza** [comment]
> This addition would allow us to easily check for the containerized app's health.

it can already be done with a HEAD request though?
```
$ curl -IHEAD ps-vgeoip.herokuapp.com
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 10552
Content-Type: text/html; charset=utf-8
Date: Wed, 29 Aug 2018 01:32:40 GMT
Last-Modified: Wed, 09 May 2018 08:36:57 GMT
Via: 1.1 spaces-router (575c1342addb)
```

**Comment by ignatiusreza** [comment]
> This addition would allow us to easily check for the containerized app's health.

it can already be done with a HEAD request though?
```
$ curl -IHEAD freegeoip.io
HTTP/1.1 200 OK
Date: Wed, 29 Aug 2018 01:34:13 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d254df5b714ce465be0606ac739a902271535506453; expires=Thu, 29-Aug-19 01:34:13 GMT; path=/; domain=.freegeoip.io; HttpOnly
Last-Modified: Tue, 08 May 2018 14:08:45 GMT
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 451b4623d6819505-NRT
```

**Comment by saveav** [comment]
Ah yes.

Will try using `HEAD` on Fargate for health check...

**Comment by saveav** [comment]
Got used to adding `/ping` and `pong`...

**Comment by saveav** [comment]
Closing this because it doesn't occur regularly, seems to be edge case, so it's not that required

**Pull request closed without merging**
